"""Train the 0DTE Rough Volatility surrogate model.

Trains the same architecture as the main pricer but specifically on the
0DTE dataset generated by the Rough Bergomi Monte Carlo engine.
Because rough vol pathwise Greeks are complex, this uses standard price MSE.

The near-expiry price surface has a sharp ATM kink, which a single short
run underfits badly (~30 bps true error vs ~2 bps label noise) — so this
trains a deep ensemble with a longer cosine schedule, mirroring the main
pricer's recipe.

Usage:  python -m backend.quant.train_0dte --ensemble 5 --epochs 500
"""
import argparse
import json
import math
import time
from pathlib import Path
import torch
import torch.nn as nn
from backend.quant.model import AsianPricerNet

ARTIFACTS = Path(__file__).resolve().parents[2] / "artifacts"

def normalize_0dte(X: torch.Tensor) -> torch.Tensor:
    # Bounds for 0DTE:
    # Spot: [85.0, 115.0] (Spot/Strike where Strike=100) -> [0.85, 1.15]
    # Maturity: [1/252.0, 12/252.0]
    # Sigma: [0.05, 0.80]
    # Rate: [0.0, 0.10]
    lows = torch.tensor([0.85, 1/252.0, 0.05, 0.0], dtype=torch.float32)
    highs = torch.tensor([1.15, 12/252.0, 0.80, 0.10], dtype=torch.float32)
    return 2.0 * (X - lows) / (highs - lows) - 1.0

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--ensemble", type=int, default=5)
    p.add_argument("--epochs", type=int, default=500)
    p.add_argument("--batch", type=int, default=1024)
    p.add_argument("--lr", type=float, default=2e-3)
    p.add_argument("--seed", type=int, default=11)
    args = p.parse_args()

    ds_path = ARTIFACTS / "dataset_0dte.pt"
    if not ds_path.exists():
        print("0DTE Dataset not found. Please run dataset_0dte.py first.")
        return

    print(f"Loading {ds_path}...")
    ds = torch.load(ds_path, map_location="cpu", weights_only=True)
    X = ds["X"]
    y = ds["y"]
    # dynamics the dataset was generated under (persisted by dataset_0dte);
    # older datasets predate this field and used the historical defaults
    dyn = ds.get("params", {"eta": 1.5, "rho": -0.7, "H": 0.1})
    print(f"dataset dynamics: {dyn}")

    # Whether these dynamics came from a market calibration is a FACT ABOUT THE
    # DATASET, so read it from the calibration the same way dataset_0dte did,
    # and check the parameters actually match. The alternative — trusting the
    # artifact to still describe reality — is how the checkpoint ended up
    # announcing "uncalibrated defaults" while carrying eta=2.688 from a live
    # SPY fit.
    calibrated, note = False, (
        "Historical defaults (eta 1.5, rho -0.7, H 0.1); no market calibration "
        "was adopted. Run 'python -m backend.quant.calibrate --retrain' during "
        "market hours to fit and adopt live dynamics.")
    cal_file = ARTIFACTS / "rough_calibration.json"
    if cal_file.exists():
        cal = json.loads(cal_file.read_text())
        same = all(abs(float(dyn[k]) - float(cal[k])) < 1e-9
                   for k in ("eta", "rho", "H") if k in cal and k in dyn)
        if same and cal.get("accepted") and cal.get("kernel") == dyn.get("kernel"):
            calibrated = True
            note = (f"Calibrated to {cal.get('ticker', '?')} on "
                    f"{cal.get('as_of', '?')}: {cal.get('n_quotes', '?')} "
                    f"quotes ({cal.get('quote_source', '?')}) across "
                    f"{len(cal.get('expiries', []))} expiries, implied-vol "
                    f"RMSE {cal.get('iv_rmse_volpts', '?')} vol points, "
                    f"accepted by calibrate.quality_gate.")
    print(f"calibrated: {calibrated} — {note}")

    # Exclude any NaNs
    valid = ~torch.isnan(y)
    X = X[valid]
    y = y[valid]

    Xn = normalize_0dte(X)

    # train/val split (shared across members)
    torch.manual_seed(args.seed)
    n_val = max(int(0.1 * len(Xn)), 1)
    perm = torch.randperm(len(Xn))
    val_idx, tr_idx = perm[:n_val], perm[n_val:]
    Xtr, ytr = Xn[tr_idx], y[tr_idx]
    Xva, yva = Xn[val_idx], y[val_idx]

    loss_fn = nn.MSELoss()
    steps_per_epoch = math.ceil(len(Xtr) / args.batch)
    member_states = []
    member_val = []

    for member in range(args.ensemble):
        torch.manual_seed(args.seed + 1000 * (member + 1))
        model = AsianPricerNet(width=128, n_blocks=4)
        opt = torch.optim.AdamW(model.parameters(), lr=args.lr,
                                weight_decay=1e-5)
        sched = torch.optim.lr_scheduler.CosineAnnealingLR(
            opt, T_max=args.epochs)

        best_val = math.inf
        best_state = None
        t0 = time.perf_counter()
        for epoch in range(1, args.epochs + 1):
            model.train()
            ep_perm = torch.randperm(len(Xtr))
            total = 0.0
            for i in range(steps_per_epoch):
                idx = ep_perm[i * args.batch:(i + 1) * args.batch]
                opt.zero_grad(set_to_none=True)
                loss = loss_fn(model(Xtr[idx]), ytr[idx])
                loss.backward()
                opt.step()
                total += loss.item() * len(idx)
            sched.step()

            model.eval()
            with torch.no_grad():
                val_rmse = math.sqrt(loss_fn(model(Xva), yva).item())
            if val_rmse < best_val:
                best_val = val_rmse
                best_state = {k: v.detach().clone()
                              for k, v in model.state_dict().items()}
            if epoch % 50 == 0 or epoch == 1:
                print(f"member {member + 1}/{args.ensemble}  "
                      f"epoch {epoch:>4}/{args.epochs}  "
                      f"train mse {total / len(Xtr):.3e}  "
                      f"val rmse {val_rmse:.3e}  "
                      f"({time.perf_counter() - t0:5.1f}s)", flush=True)

        member_states.append(best_state)
        member_val.append(best_val)
        print(f"member {member + 1} done: val rmse {best_val * 1e4:.1f} bps",
              flush=True)

    # ensemble validation
    with torch.no_grad():
        probe = AsianPricerNet(width=128, n_blocks=4)
        preds = []
        for state in member_states:
            probe.load_state_dict(state)
            probe.eval()
            preds.append(probe(Xva))
        ens_rmse = math.sqrt(loss_fn(torch.stack(preds).mean(0), yva).item())

    print(f"Training done. Ensemble val RMSE: {ens_rmse * 1e4:.1f} bps "
          f"of strike (members: "
          f"{', '.join(f'{v * 1e4:.1f}' for v in member_val)})")
    torch.save({"members": member_states,
                "meta": {"0dte": True, "normalize": "0dte_bounds",
                         "n_members": len(member_states),
                         "val_rmse_bps": ens_rmse * 1e4,
                         "model": "rough_bergomi",
                         "H": float(dyn["H"]), "eta": float(dyn["eta"]),
                         "rho": float(dyn["rho"]),
                         "kernel": dyn.get("kernel", "type_I_fbm_LEGACY"),
                         # DERIVED from the dataset, never hardcoded. This was
                         # pinned to False with a note explaining that the then
                         # current calibration was unusable — true when written,
                         # and silently false the moment a good fit was adopted.
                         # A checkpoint carrying eta=2.688 from a live SPY fit
                         # while announcing "uncalibrated defaults" misinforms
                         # exactly the person who thought to check.
                         "calibrated": calibrated,
                         "calibration_note": note,
                         "epochs": args.epochs, "lr": args.lr,
                         "batch": args.batch, "seed": args.seed}},
               ARTIFACTS / "model_0dte.pt")
    print(f"Saved {ARTIFACTS / 'model_0dte.pt'}")

if __name__ == "__main__":
    main()
